mutation($theme: String!, $iconset: String!, $darkMode: Boolean!, $sidebarEnabled: Boolean!, $sidebarAlignment: String!, $tocEnabled: Boolean!, $injectCSS: String, $injectHead: String, $injectBody: String) {
  theming {
    setConfig(theme: $theme, iconset: $iconset, darkMode: $darkMode, sidebarEnabled: $sidebarEnabled, sidebarAlignment: $sidebarAlignment, tocEnabled: $tocEnabled, injectCSS: $injectCSS, injectHead: $injectHead, injectBody: $injectBody) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
